[package]
name = "fahrenheit_to_celcius"
version = "1.0.0"
authors = ["Ethanol <kigangadarell@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]